---
title: "8. Management"
format: html
---

8.1 List top management.
8.2 Summarize any recent management changes.
8.3 Provide management biographies.
8.4 Compile management compensation.
8.5 What other corporations are top managers associated with?
8.6 List any other news items about management (social clubs, political activity).
8.7 List management consultant/union buster.

The organization’s web site is the best way to find out information about nonprofit managers.  While Form 990 does not provide general information on managers, both Part VII and Schedule O report the compensation of officers, directors, trustees, key employees, and the highest compensated employees.

Note that on Line 25a of Part IV of Form 990 requires the filer to indicate if the organization paid an Excess Benefit to any employee.  This would be any salary or benefits package significantly higher than the compensation received by officers of similar organizations. This excess benefit is taxable and more detail is provided in Schedule L.

Section A of Part VI of Form 990 provides detailed information on the Governing Body and Management.  This includes information on the number of voting members, whether there are business or family relationships between the board and management and a variety of questions on how decisions are made may tell you a great deal about how the nonprofit is managed.

Candid, the National Center for Charitable Statistics (NCCS), and the Economic Research Institute all provide access to Form 990 as well as summary information on nonprofit organizations. Also check the New York Charities Bureau.

Use a gen­eral news search and social media to find out more about management’s cur­rent activities.

When doing news searches, make sure to go to local news­pa­pers and media out­lets in the city in which the firm is located. Some of this infor­ma­tion many not show up in a gen­eral search.

Firms and top man­age­ment are increasingly using a vari­ety of social media and it is becom­ing an impor­tant research tool. LinkedIn is a pop­u­lar busi­ness social-networking site. You need to be a mem­ber to search (mem­ber­ship is free) and you can search by com­pa­nies as well as indi­vid­u­als. Face­book is becoming very pop­u­lar with indi­vid­u­als and firms, and can be a great source of infor­ma­tion. You need to be a mem­ber but mem­ber­ship is free.

You can use the Union Busters Alerts database to find out if a nonprofit organization has hired a management consultant/union buster.