---
title: "10. Board of Directors"
format: html
---

10.1 List Board mem­bers and their compensation.
10.2 Sum­ma­rize any recent Board changes.
10.3 Pro­vide biogra­phies of Board mem­bers.
10.4 What other cor­po­ra­tions are Board mem­bers asso­ci­ated with? Are they impor­tant? Why?
10.5 List any other news items about Board mem­bers (social clubs, polit­i­cal activ­ity).
10.6 Sum­ma­rize which Board mem­bers are most vulnerable.

The organization’s web site is likely the best way to fund out information about its directors/board members.  While Form 990 does not provide general information on managers, both Part VII and Schedule O report the compensation of officers, directors, trustees, key employees, and the highest compensated employees.

Section A of Part VI of Form 990 provides detailed information on the Governing Body and Management.  This includes information on the number of voting members, whether there are business or family relationships between the board and management and a variety of questions on how decisions are made may tell you a great deal about the role of the board in the organization.

Candid, the National Center for Charitable Statistics (NCCS), and the Economic Research Institute all provide access to Form 990 as well as summary information on nonprofit organizations. Also check the New York Charities Bureau.

Beyond this basic infor­ma­tion, use a gen­eral news search and social media to gather more detailed infor­ma­tion on board members.