---
title: "13. Subsidiaries"
format: html
---

13.1 List sub­sidiary organizations.
13.2 Do funds flow between the parent and local organizations?

Nonprofits may be single freestanding organizations or part of a larger organization. If the parent organization is responsible for the finances of the local organizations, the local organizations are not required to file Form 990. Even if they are financially independent, some funds may flow between them. Parent organizations may contribute to local organizations or fundraising from local organizations may flow to the parent organization.

Part VIII Statement of Revenue on Form 990 lists donations and other contributions where it may be possible to ascertain this exchange of funds.

Lines 34-37 of Part VI of Form 990, along with Schedule R, provide information on if the nonprofit is financially involved with a related organization.

Candid, the National Center for Charitable Statistics (NCCS), and the Economic Research Institute all provide access to Form 990 as well as summary information on nonprofit organizations. Also check the New York Charities Bureau.

This information may also be available on the organization’s web site.