---
title: "14. Sector and Industry"
format: html
---

14.1 What is the core sector?
14.2 What is the name of the sector pub­li­ca­tion?
14.3 What are the cur­rent trends in the sector?

The NTEE you iden­ti­fied in Ques­tion 2 will allow you to iden­tify the sector (or sectors) in which the organization is oper­at­ing. The best way to learn about a sector is to con­sult sector pub­li­ca­tions, if they are available. You can find these using a gen­eral news search or by con­sult­ing Web Wire. Indus­try pub­li­ca­tions often pro­vide a great deal of infor­ma­tion about cur­rent trends in the indus­try, as well as com­par­a­tive data on the industry’s top players.

Sometimes nonprofits operate in a sector or industry that also includes private sector firms. In these cases you can go to Yahoo Finance,  and use the “indus­try” tab to learn more about the indus­try in which your firm is located.

Paid Resources (Requires Subscription)

CFRA’s MarketScope Advisor provides reports on selected industries and individual firms. IBIS World provide slightly less comprehensive reports but on a much wider variety of industries. Business Insights: Essentials also provides basic information on industries, and Mintel looks specifically at retailing, healthcare, technology and tourism.