---
title: "15. Competitors"
format: html
---

15.1 Iden­tify the top three com­peti­tors.
15.2 To what degree are these other employ­ers true com­peti­tors? Do they actu­ally sup­ply the same type of ser­vice?
15.3 What are the per­cent­ages of the sector or indus­try that your tar­get firm and each of its major com­peti­tors con­trol?
15.4 Is one of these firms emerg­ing as a leader?

It is important to understand your target organization in terms of the competitive landscape. Some nonprofits provide unique services, while others operate in sectors where there is competition from other nonprofits and for profit firms.  It may be difficult to find information on competitors as it is not contained on Form 990 or it is unlikely that it will appear on the organization’s web site.  Industrial/sectoral publications may provide information as well as a general news search.

When eval­u­at­ing com­peti­tors, it is impor­tant to iden­tify if they are true com­peti­tors. Do they actu­ally offer similar services and have sim­i­lar clients or customers?