---
title: "17. Transportation, Distribution, and Dissemination"
format: html
---

17.1 How do sup­plies, prod­ucts, ser­vices, or clients leave the facil­i­ties?
17.2 Are any of these forms of transportation/distribution/dissemination unionized?

Work­ers are the best source for iden­ti­fy­ing forms of trans­porta­tion, dis­tri­b­u­tion and dissemination. Some information on transportation may be available on Form 990. Section B of Part VII of the 990 lists the five highest compensated independent contractors.  In some instances this may include a major supplier of goods or services.  While Part IX the Statement of Function Expenses does not list specific suppliers, it does provide a general list of expenses, which may include transportation. Candid, the National Center for Charitable Statistics (NCCS), and the Economic Research Institute all provide access to Form 990 as well as summary information on nonprofit organizations. Also check the New York Charities Bureau.

You may find infor­ma­tion on the organization’s truck fleet, as well as their safety record, at the Fed­eral Motor Car­rier Safety Admin­is­tra­tion. The National Trans­porta­tion Safety Board also com­piles acci­dent infor­ma­tion on all types of transportation.