---
title: "22. Other Regulatory and Legal"
format: html
---

22.1 Are there other spe­cific reg­u­la­tory agen­cies that gov­ern this com­pany (such as health care reg­u­la­tions in hos­pi­tals and nurs­ing homes)?
22.2 List any inci­dents or vio­la­tions.
22.3 List any legal actions taken or pend­ing against the com­pany.
22.4 List any NLRB charges or findings.

Use indus­try pub­li­ca­tions to iden­tify if there are reg­u­la­tory agen­cies that gov­ern your tar­get employ­er. Work­ers may also know about spe­cific reg­u­la­tors. A gen­eral news search may also pro­vide insights.

Underwriters Laboratories (UL)  develop many industry standards in the U.S.

The National Labor Rela­tions Board (NLRB) main­tains a data­base where you can inves­ti­gate recent NLRB activ­ity. It is a free site but you must first reg­is­ter. You can search by com­pany to iden­tify if there has been recent NLRB activ­ity at your firm.

The Stan­ford Law School’s Secu­ri­ties Class Action Clear­ing House pro­vides a vari­ety of infor­ma­tion on firms gath­ered under the Pri­vate Secu­ri­ties Lit­i­ga­tion Reform Act.

Paid Resources (Requires Subscription)

You can search for addi­tional legal infor­ma­tion on NewsBank.