---
title: "23. Community"
format: html
---

23.1 Describe the organization’s com­mu­nity rela­tions.
23.2 Are there com­mu­nity issues with the organization and its oper­a­tions?
23.3 List any iden­ti­fi­able com­mu­nity orga­ni­za­tions that could be enlisted as allies.
23.4 What are the major unions and cen­tral labor bod­ies in the com­mu­ni­ties where both the com­pany and the par­ent com­pany are located (both here and abroad), and how could they be used as allies in the campaign?

Work­ers are the best source for com­mu­nity issues. A gen­eral news search and a search of social media may pro­vide addi­tional information. Some information may also be available on the organization’s web site.

The AFL-CIO and Change to Win pro­vide links to labor orga­ni­za­tions. Jobs with Jus­tice will put you in touch with local labor activists.

Mapping the Common Good provides a map of union contract expirations across the United States, which can help organizers coordinate a campaign with community groups.