---
title: "24. Political"
format: html
---

24.1 How is the com­pany con­nected polit­i­cally on the local, state, and national level?
24.2 List polit­i­cal con­tri­bu­tions.
24.3 List any top man­age­ment or board mem­bers who are involved in political activity or who in the past held polit­i­cal positions.
24.4 What are the lobbying activities?

Under IRS rules 501(c ) 3 organizations may not engage in partisan politics.  They may however be involved in non-partisan politics.  They can also be directly involved in lobbying, allocating up to 20% of the first $500,000 of their budget, and more than $1 million annually.  Schedule C of the Form 990 provides a great deal of information on the organization’s lobbying activities. Candid, the National Center for Charitable Statistics (NCCS), and the Economic Research Institute all provide access to Form 990 as well as summary information on nonprofit organizations. Also check the New York Charities Bureau.

Other 501(c ) organizations may be engaged in partisan political activities. The Cen­ter for Respon­sive Pol­i­tics pro­vides com­pre­hen­sive infor­ma­tion on polit­i­cal con­tri­bu­tions at all lev­els of the fed­eral gov­ern­ment. You can search by both employ­ers and indi­vid­u­als. Con­sult state web sites for the avail­abil­ity of sim­i­lar infor­ma­tion at the state level.

Fol­low the Money, the National Insti­tute on Money in State Politics’ web site, pro­vides com­pre­hen­sive infor­ma­tion on state pol­i­tics. The Fed­eral Elec­tion Com­mis­sion pro­vides basic infor­ma­tion on polit­i­cal donors, as well as polit­i­cal action committees.