project:
  type: website

website:
  title: "Fresno Building Healthy Communities"
  description: "Strategic Corporate Research"
  sidebar: 
    style: "floating"
    contents: 
      - text: "1. Basic Information" 
        href: 01_basic_information.qmd
      - text: "2. Products and Services"
        href: 02_products_services.qmd
      - text: "3. Facilities"
        href: 03_facilities.qmd
      - text: "Bibliography"
        href: 99_bibliography.qmd

format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true
    toc-depth: 5
    
execute: 
  echo: false
  output: false
  warning: false
  
bibliography: references.bibtex
csl: diabetologia.csl