---
title: "Executive Summary"
format: html
---

This report provides strategic corporate research regarding Community Hospitals of Central California (CHCC) @community_medical_centers also known as Community Medical Centers @cmcenters. Cultiva la Salud @cultiva_la_salud has filed a petition for writ of mandate and complaint @writ_of_mandate against CHCC alleging that:

> Respondents have failed to spend Supplemental Medi-Cal funds as required by statute—to improve access to care and the quality of that care for the Black and Latino low-income patients reliant on Fresno CRMC for their medical care—instead spending the funding to enhance Respondents’ suburban facility, Clovis CMC, which serves a much wealthier, whiter, and healthier population, and far fewer Medi-Cal beneficiaries.

This document provides background information on CHCC including details on its services, facilities, workforce, finances, company history, and other topics that could be of use in creating a strategic campaign to force CHCC to meet the needs of the Fresno CRMC community.

  
The framework for this report is taken from the [strategic corporate research guide ](https://strategiccorporateresearch.org/) website. And its chapters correspond to the 24 question model described in Juravich's "Beating Global Capital" @beating_global_capital.